spring:
  application:
    name: snippet-manager
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:db-manager}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI:https://dev-dxazwu1rijz501rx.us.auth0.com/}
          client-id: ${AUTH_CLIENT_ID:client_id}
          client-secret: ${AUTH_CLIENT_SECRET:client_secret}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
auth0:
  audience: ${AUTH0_AUDIENCE:https://dev-dxazwu1rijz501rx.us.auth0.com/}

